version: "2"

services:
  dummy:
    image: malte311/dummy-webapp
    #build: .
    container_name: webapp
    ports:
      - "80:80"
    volumes:
      - ./deny/:/php-code/deny/ 
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment: 
      - WATCHTOWER_POLL_INTERVAL=60
